version: 0.0
os: linux

files:
  - source:  /Backend/mcthemax/
    destination: /home/ubuntu/build
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /Backend/mcthemax/scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: /Backend/mcthemax/scripts/start.sh
      timeout: 60
      runas: ubuntu