spring:
#  datasource:
#    url : ${RDS_HOSTNAME}
#    username : ${RDS_USERNAME}
#    password : ${RDS_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: mysql, s3
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true

