cloud:
  aws:
    s3:
      bucket: mcthemax-pdf
    stack:
      auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: AKIAVR2UNDLQ7OKIGC7I
      secret-key: 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