name: Frontend S3 deploy

# master branch에 push가 발생했을 경우 아래 수행 
on:
  push:
    branches:
      - feature/#23   

jobs:
  build:
		# 실행할 os는 ubuntu:latest로 설정 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: npm install
        run:
          npm install

      - name: npm build
        run: 
          npm run build
        env:
          CI: false
					# 빌드 작업 시 기본적은 warning 로그는 모두 error로 취급
					# CI를 false로 지정할 시 warning 무시가 가능

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy AWS S3
        run: 
          aws s3 sync --delete --region ap-northeast-2 Frontend/mcthemax/build s3:::mcthemax-frontend